project:
  type: book
  output-dir: docs

book:
  title: "Symbolic Modified Nodal Analysis<br>using Python"
  author: "Tiburonboy"
  date: "1/1/2024"

  chapters:
    - index.qmd
    - Preface.qmd
    - Introduction.qmd
    - Theory.qmd
    - SMNA_example.ipynb
    - part: Code-validation.qmd
      chapters:
        - test_1.ipynb
        - test_2.ipynb   
        - test_3.ipynb  
        - test_4.ipynb  
        - test_5.ipynb  
        - test_6.ipynb  
        - test_7.ipynb  
        - test_8.ipynb  
        - test_9.ipynb  
        - test_10.ipynb  
        - test_11.ipynb  
        - test_12.ipynb  
        - test_13.ipynb  

    - part: Example-problems.qmd
      chapters:
        - Two amplifier RIAA Phono Preamp.ipynb
        - Two port parameters.ipynb
        - Thevenin equivalent circuit.ipynb
        - Chapter-D.qmd
        - Chapter-E.qmd

    - part: Appendices.qmd
      chapters:
        - Appendix_1.qmd
        - Bibliography.qmd

format:
  html:
    theme:
      - cosmo

