project:
  type: book
  output-dir: docs

book:
  title: "Symbolic Modified Nodal Analysis<br>using Python"
  author: "Tiburonboy"
  cover-image: cover_v2.png
  date: "8/16/2025"
  date-format: D MMMM YYYY

  chapters:
    - index.qmd
    - Preface.qmd
    - Introduction.qmd
    - Theory.qmd
    - SMNA_example.ipynb
    - SMNA-function.qmd
    - part: Validation-tests.qmd
      chapters:
        - test_1.ipynb
        - test_2.ipynb
        - test_3.ipynb
        - test_4.ipynb
        - test_5.ipynb
        - test_6.ipynb
        - test_7.ipynb
        - test_8.ipynb
        - test_9.ipynb
        - test_10.ipynb
        - test_11.ipynb
        - test_12.ipynb
        - test_13.ipynb
        - test_14.ipynb
        - test_15.ipynb
    - part: Example-problems.qmd
      chapters:
        - Two amplifier RIAA Phono Preamp.ipynb
        - Two port parameters.ipynb
        - Thevenin equivalent circuit.ipynb
        - State-variable-filter.ipynb
        - Superposition.ipynb
        - 2nd_order_BRF.ipynb
        - Elliptic-function-LPF.ipynb
        - Initial_conditions.ipynb
        - Transient_circuit.ipynb
        - Bridge-T.ipynb
        - Pi-Filter.ipynb
        - SIDO-low-pass-filter.ipynb
        - Super-node.ipynb
        - Phasor-analysis.ipynb
        - Modeling Op Amps.ipynb
        - Op Amp circuits.ipynb
        - mech-sys.ipynb
        - Klon Centaur part 1.ipynb
        - Klon Centaur part 2v0.ipynb
        - Klon Centaur part 3v1.ipynb
#        - Klon Centaur part 2 temp.qmd
#        - Klon Centaur part 3 temp.qmd
        - Wien bridge oscillator.ipynb
#        - Wien bridge oscillator temp.qmd
        - Flyback circuit.qmd
        - Diode circuit.qmd
        - Transistor circuit.qmd
        - Bridged T-coil temp.qmd
#        - Bridged-T-coil_v2.ipynb
    - References.qmd
  appendices:
    - SymMNA_py.qmd
    - Change-log.qmd
    - Google Colab.qmd
    - SMNA_mobile.ipynb
    - EasyEDA_schematic_editor.qmd

format:
  html:
    theme:
      - cosmo

bibliography: references.bib

