project:
  type: book
  output-dir: _book

book:
  title: "Symbolic Modified Nodal Analysis"
  subtitle: "using Python"
  author: "Jane Doe"
  date: "8/18/2018"
  reader-mode: true

  page-footer:
    left: |
      left page footer: Book Template was written by Joe Smith
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg

  chapters:
    - index.qmd
    - Front-Matter.qmd
    - Preface.qmd
    - Introduction.qmd
    - Theory.qmd

    - part: Verification.qmd
      chapters:
        - Chapter-A.qmd
        - Chapter-B.qmd   

    - part: Problems.qmd
      chapters:
        - Chapter-C.qmd
        - Chapter-D.qmd
        - Chapter-E.qmd

    - part: Appendices.qmd
      chapters:
        - Acknowledgments.qmd
        - Bibliography.qmd

format:
  html:
    theme:
      - cosmo
    toc: true

    callout-appearance: simple


