# Preface {#sec-Preface .unnumbered}

This book describes a Python coding project that I started in 2015. Over the years I've put the code on [Github](https://en.wikipedia.org/wiki/GitHub) along with some test circuits and documentation, linked [here](https://github.com/Tiburonboy/Symbolic-modified-nodal-analysis). I think I have enough content that I'm able to turn the effort into an online book.

The nodal analysis code started as a translation from some C code to generate a nodal admittance matrix that I had written in 1988. I wrote the C code for two reasons. Free versions of [SPICE](https://en.wikipedia.org/wiki/SPICE) for the PC didn't exist at the time and I wanted to use some of the code from, *Numerical Recipes in C*, @Press1992. The original C code worked well and calculated numerical solutions. I then started writing some C code to generate the matrices with symbolic values and then intended to use LISP to symbolically solve the equations. I didn’t get too far with this effort. The LISP code would generate huge symbolic strings with no simplification. The output was a big pile of trash that was not in the least bit useful or decipherable. Currently, there are many free [circuit simulators](https://en.wikipedia.org/wiki/List_of_free_electronics_circuit_simulators) available.

In 2014, I started to use Python for my coding projects and engineering calculations. There are some nice Python libraries for numeric and symbolic calculations (such as NumPy and SymPy), so I decided to try writing a Python script to generate node equations based on my old C code I had written many years before. Part way into this project I discovered that there is a new nodal analysis technique being taught today in engineering school called [modified nodal analysis](https://en.wikipedia.org/wiki/Modified_nodal_analysis) (MNA). My motivation for reviving this coding project is my continued interest in circuit analysis and synthesis.

The MNA procedure provides an algorithmic method for generating systems of independent equations for linear circuit analysis. Some of my younger colleagues at work were taught this method, but I never heard of it. These days, I never really analyze a circuit by hand, unless it’s so simple that you can almost do it by inspection. Most problems that an electrical engineer encounters on the job are complex enough that they use computers to analyze the circuits. [LTSpice](https://www.analog.com/en/design-center/design-tools-and-calculators/ltspice-simulator.html) is the version of spice that I use, since it’s free and does a good job converging when analyzing switching circuits.

My code started initially by following the code from @Cheever2022, which used [MATLAB](https://www.mathworks.com/products/matlab.html) to generate modified nodal equations. I somewhat followed his MATLAB code for resistors, capacitors, op amps and independent sources. The naming of the matrices follows his convention. The preprocessor and parser code was converted from my old C code. The use of Pandas for a data frame is new and SymPy is used to do the math; the use of element stamps is from @Palusinski2005.

Inductors are being addressed in the D matrix, which is different from the way Erik Cheever's code works. Erik's code puts inductors into the G matrix as 1/s/L. My code puts the inductor contribution into the D matrix. Coupled inductors also affect the D matrix, so it makes sense to allow the inductors to be in the D matrix rather than the G matrix.

## Survey of other symbolic circuit analysis code
The Python code presented in this notebook is somewhat unique since Python is open source, free and runs on a variety of platforms, the code presented in this IPython notebook is portable. As described in the About this book, this code is made available under a public domain license and archived in a github [repository](https://github.com/Tiburonboy/Symbolic-modified-nodal-analysis).

There are other symbolic circuit analysis codes available and some of these are described here. Some of these codes are based on commercial software such as MATLAB, [TINA](https://www.tina.com/) and [Maple](https://www.maplesoft.com/).

[SLiCAP](https://analog-electronics.tudelft.nl/SLiCAP.html) is a symbolic linear analysis tool. SLiCAP is now a Python program, but originally it was written in MATLAB.

TINA is an acronym of Toolkit for Interactive Network Analysis. The TINA design suite is a circuit simulator and PCB design software package for analyzing, designing, and real time testing of analog, digital, HDL, MCU, and mixed electronic circuits and their PCB layouts. TINA has some [symbolic analysis capability](https://www.tina.com/symbolic-analysis).

Maple is a mathematical package and there is an application [note](https://www.maplesoft.com/applications/view.aspx?SID=1427) available describing its use in symbolic circuit analysis. The application note presents a method for evaluating, solving and designing a common, but not so simple pulse-mode high-gain transimpedance amplifier or TIA circuit.

[Symbolic Circuit Analysis](https://rodanski.net/ben/work/symbolic/index.htm) is a web page devoted to symbolic circuit analysis.

[SAPWIN](http://www.ewh.ieee.org/soc/es/May2001/12/Begin.htm) is a windows program package for symbolic and numerical simulation of analog circuits.

[Lcapy](https://github.com/mph-/lcapy) is an experimental Python package for teaching linear circuit analysis. It uses SymPy for symbolic mathematics. @Hayes2022 provides an overview of Lcapy as well as a survey of symbolic circuit analysis packages.

## Chapter contents
**Chapter 1** introduces the topic of MNA and describes how Python can easily solve mathematical expressions that would be very hard and laborious to do with pencil and paper. 
**Chapter 2**, describes the theory behind MNA. **Chapter 3** walks through a circuit analysis problem from netlist generation to AC analysis and generation of a frequency response plot of the circuit. **Chapter 4** provides a description of the Python function that implements the symbolic MNA procedure. There are 15 circuits that were used to validate the Python code. These circuits range from simple circuits that you would find in textbooks, to complex circuits that would be very difficult to analyze if not for computers. There are also a couple of test circuits designed to generate sub-matrices of all zeros during the formulation of the network equations. The last part of the book is a collection of interesting circuits (at least to me) that showcase the power and ease with which the Python code can solve circuit analysis problems. The appendices contain a listing for the smna function and a change log of the history of the project's code development.

